### ISSUE TITLE
Validation in Headers and Query String

### ISSUE THREAD

**Issue by shamir92** [codingedward/flask-sieve#18]
Hi, 

May i  ask abit about validation in headers and query string? 
Is there any way currently to for this case?

**Comment by codingedward** [comment]
Hi @shamir92, 

Currently, the project just supports validating the request body but I would be open to ideas to extend its functionality so that we support the headers and the query string.

Especially if this is a feature supported by Laravel, I think we'd really need to implement that here too since the goal of this project is to provide close (if not all) features supported by Laravel validation.

Do you know (or could you point me to a resource) that shows how such validation is supported on Laravel?

**Comment by shamir92** [comment]
hi @codingedward, 
Sorry, i forget about this ticket. 
Currently I forget how it's being used in laravel. 
Hehee. If I found it later, I will create the ticket.
