### ISSUE TITLE
Custom Validation Error format Issue

### ISSUE THREAD

**Issue by RajbirSehrawat** [codingedward/flask-sieve#25]
As per documentation error response default format is 

    success: False,
    message: 'Validation error',
    errors: {
        'email': [
            'The email is required.',
            'The email must be a valid email address.'
        ],
        'password': [
            'The password confirmation does not match.'
        ]
    }
}

**But I am receiving below given. There is no success: false and message : validation errors**

{
  "email": [
    "The email field is required.", 
    "The email must be a valid email address."
  ], 
  "firstName": [
    "The firstName field is required.", 
    "The firstName may only contain letters and numbers."
  ], 
  "lastName": [
    "The lastName field is required.", 
    "The lastName may only contain letters and numbers."
  ]
}

**Comment by codingedward** [comment]
That's definitely a bug, thanks for raising it! I'll definitely work on fixing this ASAP.

**Comment by RajbirSehrawat** [comment]
I was planning to build library like this. but this is similar i was planning. It will be good if you add one more validation rule for multiple emails. 

You should also give an option to add other key-value in error response.

success: false 
message : validation errors
errors : {}

But we want to use

status: failed
message: validation errors
errors: {}

Please also think about this.

**Comment by codingedward** [comment]
Hello, sorry for the late reply on this again. Work has been a bit crazy of late. 

I have managed to work on this and I have now made the success state to be included on the response by default.

You also mentioned some other issues:
> You should also give an option to add other key-value in error response.
   
Based on the effort it would take vs the value it would add to the project I would say this is not feasible at the moment since the feature requested is more of a convenience than a necessity, I would say for now flexibility on the part of the user of the library would be appreciated. I am however open and would appreciate a PR that implements this functionality. 

> It will be good if you add one more validation rule for multiple emails.

I'm open to ideas on how we can implement this, if possible please share some resources on how Laravel may have approached this issue.
